/**
 * Props.js — set dressing and clutter. Owner: props agent.
 * Files owned: this, world/props/**.
 * Publishes: `ctx.props`.
 *
 * ── What init() does ────────────────────────────────────────────────────────────
 *   1. Resolves the prop material palette from `ctx.materials` (world/props/materials.js).
 *   2. **Sweeps the world with raycasts** to discover where the ground, the roofs and
 *      the facades actually are. Nothing in here reads the level's data tables, so a
 *      building the level agent moves takes its rooftop water tank with it.
 *   3. Runs `props/placement.js`, which composes clusters with intent — rubbish in
 *      corners, crates at loading points, stalls along the plaza, vehicles nose-in to
 *      kerbs — instead of scattering uniformly.
 *   4. Each prop is generated by `props/catalog.js` into a **prop-local** accumulator,
 *      grounded onto the surface below it (aligned to the surface normal and sunk 15 mm
 *      so there is never a gap), overlap-tested against physics and against the props
 *      already placed, then merged into its district batch.
 *   5. Districts commit to one mesh per *resolved* material (several material keys alias
 *      onto one so the merged draw-call count stays inside the budget), wrapped in a
 *      THREE.LOD whose far level keeps the big silhouettes and replaces small clutter
 *      with box shells.
 *   6. Simplified colliders go to `ctx.physics` tagged with the correct §5 surface from
 *      `ctx.materials.surfaceOf`. Mid props get dynamic bodies with real mass; small
 *      debris gets none.
 *
 * ── Public API (ctx.props) ──────────────────────────────────────────────────────
 *   ready                       boolean
 *   root                        THREE.Group added to ctx.scene
 *   spawn(type, transform, opts)-> placed | null   (see PLACEMENT OPTIONS below)
 *   list(filter?)               -> placed[]        filter: type string or predicate
 *   count(type?)                -> number
 *   rebuild(seed?)              -> stats           tear down and re-place everything
 *   types()                     -> string[]        every spawnable type
 *   remove(placed)              -> boolean
 *   footprints()                -> [{x,z,rx,rz,y0,y1,type}]  large static blockers, for AI
 *   stats                       { props, draws, triangles, colliders, dynamic, buildMs }
 *
 * ── PLACEMENT OPTIONS (third argument, or folded into the transform) ────────────
 *   x, z            world position (required unless `pos` is given)
 *   pos             [x,y,z] | Vector3, overrides x/z
 *   y               height hint; with `raw` or `onWall` it is used verbatim
 *   yaw             radians about +Y
 *   scale           uniform scale
 *   lift            extra metres above the surface (stacking)
 *   raw             skip grounding entirely — the caller owns the transform
 *   onWall          mount flush to a wall; `normal` is the wall's outward normal
 *   onRoof          ground onto the roof under `y`, not the street
 *   static          force a dynamic type to be baked static
 *   seed            extra entropy for the per-prop RNG
 *   …plus anything the generator itself understands (damage, paint, count, …)
 *
 * ── Events ──────────────────────────────────────────────────────────────────────
 *   emits `props:ready`   { count, footprints, stats }
 *   emits `props:rebuilt` { count, seed }
 *   listens `quality:changed`
 */
import * as THREE from 'three';
import { Accum, Rng, hashSeed, plainBox, discXZ, radialFadeAlpha, clamp01, TAU } from './props/geom.js';
import { PropPalette, PROP_MATS } from './props/materials.js';
import { CATALOG, TYPES } from './props/catalog.js';
import { composeScene } from './props/placement.js';

const GROUP_WORLD = 1;
const GROUP_PROP = 8;

/**
 * Merged batches. A district costs one draw call per material it uses, so the split is
 * a straight trade against frustum culling: three spatial thirds plus one global bucket
 * for debris and one for contact grime lands around 55 batched draws.
 */
const DISTRICTS = ['west', 'centre', 'east'];
const DETAIL = '_detail';
const CONTACT = '_contact';

/**
 * Triangle allowance for the whole dressing pass, per quality tier.
 *
 * Raised about a third from where it was. The old medium allowance of 100k was 5 % of
 * a 1.85 M-triangle frame and it was not enough to put something at the base of every
 * wall — which is the difference between a street and a blockout. It costs no extra
 * draw calls: everything here merges into the same per-district, per-material batches.
 */
/*
 * Raised again, by about a seventh. The dressing pass grew two whole phases — the
 * signage layer (fascias, plates, stencils, graffiti, road paint) and a much bigger
 * roofline allowance — and taking that out of the wall-line budget would have thinned
 * the pavements the last review credited. Eighteen thousand triangles on a 2.1 M frame
 * is 0.8 %, and it costs no extra draw calls: it all merges into the existing
 * per-district, per-material batches.
 */
const TRI_BUDGET = { low: 60000, medium: 150000, high: 224000, ultra: 292000 };
const DYNAMIC_BUDGET = { low: 6, medium: 14, high: 20, ultra: 26 };

const _v = new THREE.Vector3();
const _v2 = new THREE.Vector3();
const _q = new THREE.Quaternion();
const _up = new THREE.Vector3(0, 1, 0);
const _scl = new THREE.Vector3(1, 1, 1);

/**
 * The lines the map is actually looked down — the review cameras in tools/poses.js plus
 * the three main lanes. Dressing is sorted towards these so budget exhaustion produces
 * dense pockets where the player is looking rather than an even thin sprinkle nowhere.
 * [x0, z0, x1, z1] in world XZ.
 */
const SIGHTLINES = [
  [8.5, 22.0, -6.0, -14.0], // hero / night, up Souk Street
  [2.0, 10.0, 1.0, -26.0], // ads
  [-14.4, -3.2, -4.0, -9.0], // interior, market hall
  [10.0, -6.0, -10.0, -20.0], // firefight
  [-2.2, 4.4, -3.6, 1.0], // materials close-up
  [4.0, 30.0, -8.0, -48.0], // vista
  [-8.0, 14.0, -8.4, 6.0], // weapon, inside the shophouse
  [5.0, -46.0, 5.0, 28.0], // Souk Street, end to end
  [-47.0, -48.0, -47.0, 52.0], // West Alley
  [37.5, -42.0, 37.5, 28.0], // Canal Road
  [-50.0, 1.0, 46.0, 1.0], // Mid Cross
];

/** Distance from (x, z) to the nearest sightline segment. */
function sightlineDistance(x, z) {
  let best = Infinity;
  for (const [ax, az, bx, bz] of SIGHTLINES) {
    const dx = bx - ax;
    const dz = bz - az;
    const l2 = dx * dx + dz * dz;
    let t = l2 > 1e-6 ? ((x - ax) * dx + (z - az) * dz) / l2 : 0;
    t = t < 0 ? 0 : t > 1 ? 1 : t;
    const px = ax + dx * t;
    const pz = az + dz * t;
    const d = Math.hypot(x - px, z - pz);
    if (d < best) best = d;
  }
  return best;
}

/** Cheap deterministic 0..1 from a world position — used only for tie-breaking. */
function hash01(x, z) {
  const s = Math.sin(x * 127.1 + z * 311.7) * 43758.5453;
  return s - Math.floor(s);
}

/* ========================================================================== */
/*                         placed-prop footprint index                        */
/* ========================================================================== */

/** Uniform XZ grid of placed footprints — the cheap "did I already put something here". */
class FootprintGrid {
  constructor(cell = 2) {
    this.cell = cell;
    this.map = new Map();
  }
  _key(i, j) {
    return i * 8192 + j;
  }
  add(f) {
    const c = this.cell;
    const i0 = Math.floor((f.x - f.rx) / c);
    const i1 = Math.floor((f.x + f.rx) / c);
    const j0 = Math.floor((f.z - f.rz) / c);
    const j1 = Math.floor((f.z + f.rz) / c);
    for (let i = i0; i <= i1; i++) {
      for (let j = j0; j <= j1; j++) {
        const k = this._key(i, j);
        let list = this.map.get(k);
        if (!list) {
          list = [];
          this.map.set(k, list);
        }
        list.push(f);
      }
    }
  }
  /** True if `f` overlaps anything already in the grid (AABB in XZ plus a Y span test). */
  hits(f, pad = 0) {
    const c = this.cell;
    const i0 = Math.floor((f.x - f.rx - pad) / c);
    const i1 = Math.floor((f.x + f.rx + pad) / c);
    const j0 = Math.floor((f.z - f.rz - pad) / c);
    const j1 = Math.floor((f.z + f.rz + pad) / c);
    for (let i = i0; i <= i1; i++) {
      for (let j = j0; j <= j1; j++) {
        const list = this.map.get(this._key(i, j));
        if (!list) continue;
        for (const o of list) {
          if (Math.abs(o.x - f.x) > o.rx + f.rx + pad) continue;
          if (Math.abs(o.z - f.z) > o.rz + f.rz + pad) continue;
          if (o.y1 < f.y0 + 0.02 || o.y0 > f.y1 - 0.02) continue;
          return true;
        }
      }
    }
    return false;
  }
  clear() {
    this.map.clear();
  }
}

/* ========================================================================== */
/*                                   system                                   */
/* ========================================================================== */

/** @returns {import('../core/types.js').System} */
export default function createProps(ctx) {
  /** @type {THREE.Group|null} */
  let root = null;
  /** @type {PropPalette|null} */
  let palette = null;
  let contactAlpha = null;

  /** @type {Map<string, {main:Accum, shell:Accum, detail:Accum, contact:Accum}>} */
  const districts = new Map();
  /** @type {Array<object>} */
  const placed = [];
  /** @type {Array<object>} */
  const bodies = [];
  /** @type {Array<object>} */
  const dynamics = [];
  /** @type {Array<object>} */
  const lights = [];
  /** @type {THREE.Object3D[]} */
  const detailGroups = [];
  const grid = new FootprintGrid(2);
  const unsubs = [];
  const geometries = [];

  let seedBase = 0x1f2e3d4c;
  let rng = new Rng(seedBase);
  let building = false;
  let triBudget = 0;
  let dynBudget = 0;
  /** per-phase cap so the roof sweep cannot eat the whole allowance before the
   *  street-level scatter runs — see props/placement.js for the phase order */
  let phaseCap = Infinity;
  let spawnCounter = 0;

  const stats = {
    props: 0,
    rejected: 0,
    draws: 0,
    triangles: 0,
    colliders: 0,
    dynamic: 0,
    roofCells: 0,
    facadePoints: 0,
    buildMs: 0,
  };

  /* ---------------------------------------------------------------- helpers */

  function warn(msg, err) {
    // console.warn, never console.error: a bad prop must not fail the CI smoke test.
    console.warn(`[props] ${msg}`, err?.message || err || '');
  }

  function tier() {
    return ctx.settings?.tier || 'high';
  }

  function districtOf(x, y, z) {
    void y;
    void z;
    if (x < -18) return 'west';
    if (x > 17) return 'east';
    return 'centre';
  }

  function district(name) {
    let d = districts.get(name);
    if (!d) {
      d = { main: new Accum(), shell: new Accum(), detail: new Accum(), contact: new Accum() };
      districts.set(name, d);
    }
    return d;
  }

  /* ------------------------------------------------------------- raycasting */

  /**
   * Surface directly below (x, fromY, z). Returns the physics hit expanded with the
   * §5 surface tag, or null when nothing is there (a void, or outside the map).
   */
  function surfaceBelow(x, fromY, z, dist = 12) {
    const phys = ctx.physics;
    if (!phys?.raycast) {
      const gy = ctx.level?.groundY?.(x, z);
      return Number.isFinite(gy) ? { y: gy, nx: 0, ny: 1, nz: 0, surface: ctx.level?.surfaceAt?.(x, z) || 'dirt' } : null;
    }
    _v.set(x, fromY, z);
    _v2.set(0, -1, 0);
    let hit = null;
    try {
      hit = phys.raycast(_v, _v2, dist, GROUP_WORLD);
    } catch (err) {
      warn('raycast failed', err);
    }
    if (!hit) {
      const gy = ctx.level?.groundY?.(x, z);
      if (!Number.isFinite(gy)) return null;
      return { y: gy, nx: 0, ny: 1, nz: 0, surface: ctx.level?.surfaceAt?.(x, z) || 'dirt' };
    }
    return {
      y: hit.point.y,
      nx: hit.normal.x,
      ny: hit.normal.y,
      nz: hit.normal.z,
      surface: hit.surface || 'concrete',
    };
  }

  /**
   * Least-squares plane through four ground samples taken under the corners of a
   * prop's footprint. This is how a vehicle gets all four wheels on a cambered road:
   * a single probe under the origin reports the crown, and a 2.5 m wheelbase across a
   * 60 mm crown then lifts one axle clear of the tarmac.
   *
   * @returns {{y:number, nx:number, ny:number, nz:number}|null} null when the samples
   *          straddle a kerb or a step, in which case the caller keeps the flat drop.
   */
  function fitGroundPlane(x, z, yaw, bnd, scale, py) {
    const hx = Math.max(0.25, (bnd.size[0] * scale) / 2) * 0.72;
    const hz = Math.max(0.25, (bnd.size[2] * scale) / 2) * 0.72;
    const cs = Math.cos(yaw);
    const sn = Math.sin(yaw);
    let n = 0;
    let sy = 0;
    const us = [];
    const vs = [];
    const ys = [];
    for (const lx of [-hx, hx]) {
      for (const lz of [-hz, hz]) {
        const wx = x + lx * cs + lz * sn;
        const wz = z - lx * sn + lz * cs;
        const s = surfaceBelow(wx, py + 1.4, wz, 3.2);
        if (!s || s.ny < 0.55) return null;
        us.push(wx - x);
        vs.push(wz - z);
        ys.push(s.y);
        sy += s.y;
        n++;
      }
    }
    if (n < 4) return null;
    const mean = sy / n;
    // Straddling a kerb or a step: a plane through those points would tilt the whole
    // prop into the pavement. Fall back to the flat drop.
    let spread = 0;
    for (const yv of ys) spread = Math.max(spread, Math.abs(yv - mean));
    if (spread > 0.22) return null;
    let Suu = 0;
    let Svv = 0;
    let Suv = 0;
    let Suy = 0;
    let Svy = 0;
    for (let i = 0; i < n; i++) {
      const u = us[i];
      const v = vs[i];
      const d = ys[i] - mean;
      Suu += u * u;
      Svv += v * v;
      Suv += u * v;
      Suy += u * d;
      Svy += v * d;
    }
    const det = Suu * Svv - Suv * Suv;
    if (Math.abs(det) < 1e-6) return null;
    const a = (Suy * Svv - Svy * Suv) / det;
    const b = (Svy * Suu - Suy * Suv) / det;
    if (Math.abs(a) > 0.3 || Math.abs(b) > 0.3) return null;
    const inv = 1 / Math.hypot(a, 1, b);
    return { y: mean, nx: -a * inv, ny: inv, nz: -b * inv };
  }

  /** Sweep the map for flat roof decks — one entry per candidate cell. */
  function findRoofs(step = 3) {
    const b = ctx.level?.bounds;
    const minX = b ? b.min.x + 2 : -50;
    const maxX = b ? b.max.x - 2 : 48;
    const minZ = b ? b.min.z + 2 : -46;
    const maxZ = b ? b.max.z - 2 : 54;
    const cells = [];
    const key = (i, j) => i * 4096 + j;
    const found = new Map();
    for (let x = minX; x <= maxX; x += step) {
      for (let z = minZ; z <= maxZ; z += step) {
        const s = surfaceBelow(x, 32, z, 40);
        if (!s) continue;
        if (s.y < 3.2 || s.y > 14.5) continue;
        if (s.ny < 0.9) continue;
        const c = { x, z, y: s.y, surface: s.surface, edge: 99 };
        found.set(key(Math.round(x / step), Math.round(z / step)), c);
        cells.push(c);
      }
    }
    /* distance to the nearest non-roof cell — stops a tank hanging over a parapet */
    for (const c of cells) {
      const i = Math.round(c.x / step);
      const j = Math.round(c.z / step);
      let e = 99;
      for (let di = -2; di <= 2; di++) {
        for (let dj = -2; dj <= 2; dj++) {
          if (!di && !dj) continue;
          const n = found.get(key(i + di, j + dj));
          if (!n || Math.abs(n.y - c.y) > 0.6) {
            e = Math.min(e, Math.hypot(di, dj) * step);
          }
        }
      }
      c.edge = e;
    }
    return cells;
  }

  /**
   * Sweep for facade points: a world position on a wall, its outward normal, the
   * ground height in front of it and how much clear wall there is above.
   */
  function findFacades(step = 4) {
    const phys = ctx.physics;
    if (!phys?.raycast) return [];
    const b = ctx.level?.bounds;
    const minX = b ? b.min.x + 3 : -50;
    const maxX = b ? b.max.x - 3 : 48;
    const minZ = b ? b.min.z + 3 : -46;
    const maxZ = b ? b.max.z - 3 : 54;
    const out = [];
    const dirs = [
      [1, 0],
      [-1, 0],
      [0, 1],
      [0, -1],
    ];
    for (let x = minX; x <= maxX; x += step) {
      for (let z = minZ; z <= maxZ; z += step) {
        const g = surfaceBelow(x, 8, z, 14);
        if (!g || g.y > 3.0 || g.ny < 0.7) continue;
        for (const [dx, dz] of dirs) {
          _v.set(x, g.y + 1.5, z);
          _v2.set(dx, 0, dz);
          let hit = null;
          try {
            hit = phys.raycast(_v, _v2, step * 0.8, GROUP_WORLD);
          } catch {
            hit = null;
          }
          if (!hit) continue;
          const n = hit.normal;
          if (Math.abs(n.y) > 0.4) continue;
          // outward normal must face back towards the sample point
          const nx = n.x;
          const nz = n.z;
          if (nx * -dx + nz * -dz < 0.3) continue;
          // how much wall is there above this point?
          _v.set(hit.point.x + nx * 0.3, g.y + 1.5, hit.point.z + nz * 0.3);
          _v2.set(0, 1, 0);
          let up = null;
          try {
            up = phys.raycast(_v, _v2, 16, GROUP_WORLD);
          } catch {
            up = null;
          }
          const roof = surfaceBelow(hit.point.x - nx * 0.45, 32, hit.point.z - nz * 0.45, 40);
          const wallTop = roof && roof.y > 3.0 ? roof.y : 6.0;
          out.push({
            x: hit.point.x + nx * 0.02,
            z: hit.point.z + nz * 0.02,
            y: hit.point.y,
            nx,
            nz,
            groundY: g.y,
            free: Math.max(0, wallTop - g.y),
            ceiling: up ? g.y + 1.5 + up.distance : 99,
          });
        }
      }
    }
    return out;
  }

  /**
   * Find the top of the first fence or low wall along `dir` from (x, z). A perimeter
   * fence collider is a 120 mm slab, so a downward probe on a guessed offset misses it
   * almost every time: cast sideways to find the plane first, then straight down onto it.
   * @returns {{x:number,z:number,y:number}|null}
   */
  function fenceTop(x, z, dir = [1, 0], maxDist = 24) {
    const phys = ctx.physics;
    if (!phys?.raycast) return null;
    const g = surfaceBelow(x, 8, z, 14);
    const baseY = g ? g.y : 0;
    _v.set(x, baseY + 1.2, z);
    _v2.set(dir[0], 0, dir[1]).normalize();
    let hit = null;
    try {
      hit = phys.raycast(_v, _v2, maxDist, GROUP_WORLD);
    } catch {
      return null;
    }
    if (!hit) return null;
    const px = hit.point.x + _v2.x * 0.02;
    const pz = hit.point.z + _v2.z * 0.02;
    const top = surfaceBelow(px, baseY + 8, pz, 10);
    if (!top || top.y < 1.3 || top.y > 4.2 || top.ny < 0.4) return null;
    return { x: px, z: pz, y: top.y };
  }

  /* ------------------------------------------------------------- spawn core */

  /**
   * Build, ground, validate and commit one prop.
   * @returns {object|null} the placed record, or null when it was rejected
   */
  function spawn(type, transform = {}, extra = {}) {
    const def = CATALOG[type];
    if (!def) {
      warn(`unknown prop type "${type}"`);
      return null;
    }
    const o = { ...transform, ...extra };
    if (o.pos) {
      const p = o.pos;
      o.x = p.x ?? p[0];
      o.y = p.y ?? p[1];
      o.z = p.z ?? p[2];
    }
    const x = Number.isFinite(o.x) ? o.x : 0;
    const z = Number.isFinite(o.z) ? o.z : 0;
    if (building && (triBudget <= 0 || stats.triangles >= phaseCap)) {
      stats.rejected++;
      return null;
    }

    /* deterministic per-placement stream */
    const seed = hashSeed(x * 97.3, z * 89.1, (o.seed ?? 0) + spawnCounter++ * 131 + type.length * 17);
    const r = new Rng(seed ^ seedBase);

    /* ---- resolve the world transform ---------------------------------- */
    let py = Number.isFinite(o.y) ? o.y : 0;
    let nx = 0;
    let ny = 1;
    let nz = 0;
    let surface = null;
    if (o.raw) {
      // caller owns the transform
    } else if (o.onWall) {
      const n = o.normal || [0, 0, 1];
      nx = n[0];
      nz = n[2] ?? n[1] ?? 0;
    } else {
      const from = o.onRoof ? py + 1.2 : Number.isFinite(o.y) ? o.y + 2.5 : (ctx.level?.groundY?.(x, z) ?? 0) + 3.0;
      const s = surfaceBelow(x, from, z, o.onRoof ? 3.0 : 9.0);
      if (!s) {
        stats.rejected++;
        return null;
      }
      py = s.y;
      nx = s.nx;
      ny = s.ny;
      nz = s.nz;
      surface = s.surface;
    }
    if (Number.isFinite(o.lift)) py += o.lift;

    /* ---- generate into a prop-local accumulator ------------------------ */
    const local = new Accum({ tag: type });
    let res = null;
    try {
      res = def.gen(local, r, o) || {};
    } catch (err) {
      warn(`generator "${type}" threw`, err);
      return null;
    }
    if (local.isEmpty()) return null;
    const bnd = local.bounds();
    const radius = Math.max(res.radius ?? 0.5, Math.max(bnd.size[0], bnd.size[2]) * 0.5);

    /* ---- orientation ---------------------------------------------------- */
    const yaw = Number.isFinite(o.yaw) ? o.yaw : 0;
    const scale = Number.isFinite(o.scale) ? o.scale : 1;
    _q.setFromAxisAngle(_up, yaw);
    /**
     * Big footprints get a **four-corner plane fit** instead of the surface normal at
     * their origin. A carriageway carries a 50-60 mm crown (LevelData GROUND `crown`),
     * so a car sampled at one point sits with one axle in the air: the origin normal is
     * the local camber, not the plane the four wheels actually rest on. Sampling under
     * each corner and least-squares fitting a plane puts every wheel on the road.
     */
    let planeFit = null;
    if (!o.raw && !o.onWall && !o.onRoof && radius > 0.85) {
      planeFit = fitGroundPlane(x, z, yaw, bnd, scale, py);
    }
    if (planeFit) {
      py = planeFit.y;
      _v.set(planeFit.nx, planeFit.ny, planeFit.nz).normalize();
      const tilt = new THREE.Quaternion().setFromUnitVectors(_up, _v);
      _q.premultiply(tilt);
    } else if (!o.raw && !o.onWall && ny < 0.999) {
      /* tilt onto the surface normal — fully for small props, partly for big ones so a
         parked car does not look like it is climbing the camber */
      const blend = clamp01(1.15 - radius * 0.45);
      _v.set(nx, ny, nz).normalize();
      _v2.copy(_up).lerp(_v, blend).normalize();
      const tilt = new THREE.Quaternion().setFromUnitVectors(_up, _v2);
      _q.premultiply(tilt);
    }
    if (o.onWall) {
      /* +Z of the prop points out of the wall */
      _q.setFromAxisAngle(_up, Math.atan2(nx, nz));
    }

    /* sink so there is never a visible gap at the contact line */
    const sink = o.raw || o.onWall ? 0 : (o.sink ?? 0.015);
    _v.set(x, py - sink, z);
    if (o.raw || o.onWall) _v.set(x, py, z);
    const mtx = new THREE.Matrix4().compose(_v, _q, _scl.set(scale, scale, scale));

    /* ---- validation ----------------------------------------------------- */
    const fp = {
      type,
      x: _v.x,
      z: _v.z,
      rx: Math.max(0.12, (bnd.size[0] * scale) / 2),
      rz: Math.max(0.12, (bnd.size[2] * scale) / 2),
      y0: _v.y + bnd.min[1] * scale,
      y1: _v.y + bnd.max[1] * scale,
    };
    /* the footprint is axis-aligned, so rotate the half extents into world XZ */
    const ca = Math.abs(Math.cos(yaw));
    const sa = Math.abs(Math.sin(yaw));
    const rx = fp.rx * ca + fp.rz * sa;
    const rz = fp.rx * sa + fp.rz * ca;
    fp.rx = rx;
    fp.rz = rz;

    const kind = o.static && def.kind === 'dynamic' ? 'static' : def.kind || 'static';
    const flat = kind === 'flat' || res.flat;

    if (!o.force && !flat) {
      if (grid.hits(fp, 0.04)) {
        stats.rejected++;
        return null;
      }
      if (!o.onWall && !o.raw && !isClearOfWorld(_v, bnd, scale, _q, kind)) {
        stats.rejected++;
        return null;
      }
      if (!o.onWall && !o.raw && nearSpawnPoint(_v.x, _v.z, radius)) {
        stats.rejected++;
        return null;
      }
    }
    if (!flat) grid.add(fp);

    /* ---- commit ---------------------------------------------------------- */
    const rec = {
      id: placed.length + 1,
      type,
      kind,
      position: _v.clone(),
      quaternion: _q.clone(),
      scale,
      radius,
      bounds: bnd,
      surface,
      colliders: [],
      object: null,
      body: null,
      footprint: fp,
      triangles: local.tris,
    };

    const runtime = !building;
    if (kind === 'dynamic' && (runtime || dynBudget > 0)) {
      commitDynamic(rec, local, res, mtx, r);
      if (!runtime) dynBudget--;
    } else if (kind === 'solo' || runtime) {
      // A district batch is already committed to a mesh by the time a runtime spawn
      // arrives, so anything spawned after init gets its own object.
      commitSolo(rec, local, res, mtx, r);
    } else {
      commitBatched(rec, local, res, mtx, r, kind, flat);
    }

    /* contact grime under anything that meets the ground */
    if (building && !o.onWall && !o.raw && !flat && radius > 0.22) addContact(rec, r);

    /* practicals */
    if (res.lights?.length && lights.length < 12 && ctx.lighting?.addLight) {
      for (const l of res.lights) {
        _v2.set(l.pos[0], l.pos[1], l.pos[2]).applyMatrix4(mtx);
        try {
          const h = ctx.lighting.addLight({
            type: l.kind === 'spot' ? 'spot' : 'point',
            position: [_v2.x, _v2.y, _v2.z],
            color: l.color ?? 0xffd6a0,
            intensity: l.intensity ?? 6,
            radius: l.distance ?? 10,
            priority: 0.45,
            flicker: { amount: 0.05, speed: 7 },
          });
          if (h) lights.push(h);
        } catch (err) {
          warn('addLight failed', err);
        }
      }
    }

    triBudget -= local.tris;
    stats.triangles += local.tris;
    stats.props++;
    placed.push(rec);
    return rec;
  }

  /** Merge into the district batch and register static colliders. */
  function commitBatched(rec, local, res, mtx, r, kind, flat) {
    const d = district(districtOf(rec.position.x, rec.position.y, rec.position.z));
    const uvOff = [r.range(0, 3), r.range(0, 3)];
    // Only genuinely droppable debris goes to the detail bucket; a bollard is small
    // but it is cover, so it stays in the main batch.
    const target = flat ? district(DETAIL).detail : d.main;
    target.merge(local, mtx, uvOff);
    /* LOD-1 shell: keep big silhouettes verbatim, box-shell the mid stuff, drop debris */
    if (!flat && CATALOG[rec.type]?.lod !== false) {
      if (rec.radius > 1.1) d.shell.merge(local, mtx, uvOff);
      else if (rec.radius > 0.3) shellFrom(d.shell, local, res, mtx);
    }
    if (kind !== 'flat') registerStatic(rec, res, mtx);
  }

  /** Its own mesh + a LOD, for anything spawned at runtime or explicitly solo. */
  function commitSolo(rec, local, res, mtx, r) {
    const g = new THREE.Group();
    g.name = `prop:${rec.type}:${rec.id}`;
    g.position.copy(rec.position);
    g.quaternion.copy(rec.quaternion);
    g.scale.setScalar(rec.scale);
    const near = new THREE.Group();
    for (const [mat, geo] of local.buildGrouped((k) => palette.get(k))) {
      geometries.push(geo);
      const m = new THREE.Mesh(geo, mat);
      m.castShadow = true;
      m.receiveShadow = true;
      tagMesh(m, local, mat);
      near.add(m);
    }
    const shell = new Accum();
    shellFrom(shell, local, res, null); // prop-local: the group transform places it
    if (!shell.isEmpty()) {
      const far = new THREE.Group();
      for (const [mat, geo] of shell.buildGrouped((k) => palette.get(k))) {
        geometries.push(geo);
        const m = new THREE.Mesh(geo, mat);
        m.castShadow = true;
        far.add(m);
      }
      const lod = new THREE.LOD();
      lod.addLevel(near, 0);
      lod.addLevel(far, 42);
      g.add(lod);
    } else {
      g.add(near);
    }
    root.add(g);
    rec.object = g;
    void r;
    registerStatic(rec, res, mtx);
  }

  /** A real rigid body: shootable, shovable, and flagged for the velocity buffer. */
  function commitDynamic(rec, local, res, mtx, r) {
    const g = new THREE.Group();
    g.name = `prop:${rec.type}:${rec.id}`;
    for (const [mat, geo] of local.buildGrouped((k) => palette.get(k))) {
      geometries.push(geo);
      const m = new THREE.Mesh(geo, mat);
      m.castShadow = true;
      m.receiveShadow = true;
      // Motion blur / TAA reprojection: the velocity pass looks for this.
      m.userData.dynamic = true;
      tagMesh(m, local, mat);
      g.add(m);
    }
    g.userData.dynamic = true;
    g.userData.propType = rec.type;
    root.add(g);
    rec.object = g;

    const c = (res.colliders && res.colliders[0]) || null;
    const half = c?.halfExtents || [rec.radius * 0.7, Math.max(0.1, rec.bounds.size[1] / 2), rec.radius * 0.7];
    const cy = c?.pos?.[1] ?? rec.bounds.size[1] / 2;
    /* the body sits at the collider centre; the mesh is offset back by that amount */
    const off = new THREE.Vector3(c?.pos?.[0] ?? 0, cy, c?.pos?.[2] ?? 0).applyQuaternion(rec.quaternion);
    const bodyPos = rec.position.clone().add(off);
    let body = null;
    try {
      body = ctx.physics?.addBody?.({
        type: 'box',
        halfExtents: [half[0] * rec.scale, half[1] * rec.scale, half[2] * rec.scale],
        pos: bodyPos,
        quat: rec.quaternion,
        mass: (res.mass ?? CATALOG[rec.type]?.mass ?? 20) * (0.85 + r.next() * 0.3),
        material: c?.material || c?.surface || 'wood',
        surface: c?.surface || 'wood',
        group: GROUP_PROP,
        linearDamping: 0.12,
        angularDamping: 0.22,
      });
    } catch (err) {
      warn('dynamic body failed', err);
    }
    if (body) {
      body.entity = rec;
      body.userData = body.userData || {};
      body.userData.propType = rec.type;
      bodies.push(body);
      rec.body = body;
      dynamics.push({ rec, body, offset: new THREE.Vector3(c?.pos?.[0] ?? 0, cy, c?.pos?.[2] ?? 0) });
      stats.dynamic++;
    } else {
      /* no physics: fall back to a static placement so the prop is still there */
      g.position.copy(rec.position);
      g.quaternion.copy(rec.quaternion);
      registerStatic(rec, res, mtx);
      return;
    }
    g.position.copy(bodyPos).sub(off);
    g.quaternion.copy(rec.quaternion);
  }

  /** Transform prop-local colliders into world space and hand them to physics. */
  function registerStatic(rec, res, mtx) {
    const list = res.colliders || [];
    for (const c of list) {
      const p = c.pos || [0, 0, 0];
      _v2.set(p[0], p[1], p[2]).applyMatrix4(mtx);
      const half = c.halfExtents || [0.2, 0.2, 0.2];
      try {
        const body = ctx.physics?.addStatic?.({
          type: c.type || 'box',
          halfExtents: [half[0] * rec.scale, half[1] * rec.scale, half[2] * rec.scale],
          pos: { x: _v2.x, y: _v2.y, z: _v2.z },
          quat: rec.quaternion,
          surface: c.surface || 'concrete',
          material: c.material || c.surface || 'concrete',
          group: GROUP_PROP,
          tag: `prop:${rec.type}`,
        });
        if (body) {
          body.entity = rec;
          bodies.push(body);
          rec.colliders.push(body);
          stats.colliders++;
        }
      } catch (err) {
        warn('collider rejected', err);
      }
    }
  }

  /** Box-shell LOD derived from the prop's own colliders (or its bounds). */
  function shellFrom(dst, local, res, mtx) {
    const key = dominantMaterial(local);
    const list = res?.colliders?.length
      ? res.colliders
      : [
          {
            halfExtents: [
              Math.max(0.05, local.bounds().size[0] / 2),
              Math.max(0.05, local.bounds().size[1] / 2),
              Math.max(0.05, local.bounds().size[2] / 2),
            ],
            pos: [0, local.bounds().min[1] + local.bounds().size[1] / 2, 0],
          },
        ];
    for (const c of list) {
      const h = c.halfExtents || [0.2, 0.2, 0.2];
      const p = c.pos || [0, 0, 0];
      const pr = plainBox(h[0] * 2, h[1] * 2, h[2] * 2);
      const m = new THREE.Matrix4().makeTranslation(p[0], p[1], p[2]);
      if (mtx) m.premultiply(mtx);
      dst.add(key, pr, m, { grime: 0.7 });
    }
  }

  function dominantMaterial(acc) {
    let best = 'concrete';
    let n = -1;
    for (const [k, g] of acc.groups) {
      if (g.i.length > n) {
        n = g.i.length;
        best = k;
      }
    }
    return best;
  }

  function tagMesh(mesh, acc, mat) {
    mesh.userData.codMaterial = mat?.userData?.codMaterial || null;
    mesh.userData.surface = mat?.userData?.surface || 'concrete';
    mesh.userData.prop = true;
    void acc;
  }

  /**
   * Soft dirt patch welding a prop to the ground. The decal system owns this if it is
   * up; otherwise we bake our own merged patch, which costs exactly one draw call for
   * the whole map and never leaves a prop looking like it is hovering.
   */
  function addContact(rec, r) {
    const R = Math.min(2.6, rec.radius * r.range(1.25, 1.7));
    if (ctx.decals?.placeStatic) {
      try {
        const placed2 = ctx.decals.placeStatic({
          position: rec.position,
          normal: { x: 0, y: 1, z: 0 },
          // the projector pays per covered pixel; a 5 m box for a parked car is
          // waste, and the falloff already reads at ~2.5 m
          size: Math.min(2.8, R * 1.35),
          rotation: r.range(0, TAU),
          type: 'grime',
          surface: rec.surface || 'concrete',
        });
        if (placed2) return;
      } catch {
        /* fall through to the baked patch */
      }
    }
    const d = district(CONTACT);
    const pr = discXZ(R, 12);
    const m = new THREE.Matrix4().makeTranslation(rec.position.x, rec.position.y + 0.012, rec.position.z);
    d.contact.add('contact', pr, m, {
      grime: 1,
      uvFn: (lx, ly, lz) => [lx / (2 * R) + 0.5, lz / (2 * R) + 0.5],
    });
  }

  /* --------------------------------------------------------------- validation */

  /** Does this prop intersect level geometry? Tested above the ground so the floor
   *  itself never counts as a collision. */
  function isClearOfWorld(pos, bnd, scale, quat, kind) {
    const phys = ctx.physics;
    if (!phys?.overlapBox) return true;
    const hx = Math.max(0.05, (bnd.size[0] * scale) / 2 - 0.06);
    const hz = Math.max(0.05, (bnd.size[2] * scale) / 2 - 0.06);
    const lo = Math.max(0.14, bnd.min[1] * scale + 0.14);
    const hi = Math.max(lo + 0.05, bnd.max[1] * scale - 0.06);
    const hy = (hi - lo) / 2;
    _v2.set(0, lo + hy, 0).applyQuaternion(quat).add(pos);
    try {
      const hits = phys.overlapBox(_v2, { x: hx, y: hy, z: hz }, quat, GROUP_WORLD);
      if (!hits || hits.length === 0) return true;
      // a prop deliberately leaning on something is allowed one contact
      return kind === 'attach' && hits.length <= 1;
    } catch {
      return true;
    }
  }

  function nearSpawnPoint(x, z, radius) {
    const sp = ctx.level?.spawnPoints;
    if (!sp?.length) return false;
    const r2 = (radius + 1.3) * (radius + 1.3);
    for (const s of sp) {
      const p = s.pos || s.position;
      if (!p) continue;
      const dx = (p.x ?? p[0]) - x;
      const dz = (p.z ?? p[2]) - z;
      if (dx * dx + dz * dz < r2) return true;
    }
    return false;
  }

  /* ------------------------------------------------------------------ build */

  function build() {
    const t0 = now();
    building = true;
    triBudget = TRI_BUDGET[tier()] ?? TRI_BUDGET.high;
    dynBudget = DYNAMIC_BUDGET[tier()] ?? DYNAMIC_BUDGET.high;
    rng = new Rng(seedBase);
    spawnCounter = 0;

    let roofs = [];
    let facades = [];
    try {
      roofs = findRoofs(3);
    } catch (err) {
      warn('roof sweep failed', err);
    }
    try {
      facades = findFacades(4);
    } catch (err) {
      warn('facade sweep failed', err);
    }
    stats.roofCells = roofs.length;
    stats.facadePoints = facades.length;
    /**
     * Facade order decides who survives when the budget runs out. A shuffle spread the
     * survivors evenly over 100 x 100 m, which is exactly wrong: the eye reads density,
     * and a thin even sprinkle everywhere looks emptier than dense pockets somewhere.
     * Sort by distance to the sightlines the game is actually looked down, with a small
     * deterministic jitter so the result is not a monotonic sweep along one wall.
     */
    for (const f of facades) f._key = sightlineDistance(f.x, f.z) + hash01(f.x, f.z) * 2.5;
    facades.sort((a, b) => a._key - b._key);
    /**
     * Roofs get the same treatment, and for the same reason. A skyline is only worth
     * paying for where a camera can see it: an even sprinkle of water tanks over
     * 100 x 100 m spends the whole slice on rooftops behind the player. Tall roofs are
     * weighted slightly forward of low ones because they carry the actual silhouette.
     */
    for (const c of roofs) c._key = sightlineDistance(c.x, c.z) - c.y * 1.4 + hash01(c.x * 1.7, c.z * 1.3) * 3.0;
    roofs.sort((a, b) => a._key - b._key);

    const P = {
      rng,
      spawn: (type, opts) => spawn(type, opts),
      ground: (x, z, fromY) => surfaceBelow(x, fromY ?? (ctx.level?.groundY?.(x, z) ?? 0) + 3, z),
      fenceTop,
      roofs,
      facades,
      bounds: ctx.level?.bounds
        ? { minX: ctx.level.bounds.min.x, maxX: ctx.level.bounds.max.x, minZ: ctx.level.bounds.min.z, maxZ: ctx.level.bounds.max.z }
        : { minX: -50, maxX: 48, minZ: -46, maxZ: 54 },
      poi: (id) => ctx.level?.poi?.(id) || null,
      /** The whole tier allowance, so placement can size its phases as fractions. */
      total: TRI_BUDGET[tier()] ?? TRI_BUDGET.high,
      /** Open a placement phase with its own slice of the triangle allowance. */
      phase: (tris) => {
        phaseCap = Number.isFinite(tris) ? stats.triangles + tris : Infinity;
      },
      get budget() {
        return Math.min(triBudget, phaseCap - stats.triangles);
      },
    };
    try {
      phaseCap = Infinity;
      composeScene(P);
      phaseCap = Infinity;
    } catch (err) {
      warn('composition failed', err);
    }

    commitDistricts();
    building = false;
    stats.buildMs = Math.round(now() - t0);
  }

  function commitDistricts() {
    const resolve = (k) => palette.get(k);
    for (const [name, d] of districts) {
      const lod = new THREE.LOD();
      lod.name = `props:${name}`;
      const near = new THREE.Group();
      near.name = `props:${name}:near`;
      let any = false;
      for (const [mat, geo] of d.main.buildGrouped(resolve)) {
        geometries.push(geo);
        const m = new THREE.Mesh(geo, mat);
        m.name = `props:${name}:${mat.userData?.propMaterial || 'mat'}`;
        m.castShadow = true;
        m.receiveShadow = true;
        tagMesh(m, d.main, mat);
        near.add(m);
        any = true;
        stats.draws++;
      }
      /* small clutter lives in its own mesh so `low` can drop it wholesale */
      const detail = new THREE.Group();
      detail.name = `props:${name}:detail`;
      for (const [mat, geo] of d.detail.buildGrouped(resolve)) {
        geometries.push(geo);
        const m = new THREE.Mesh(geo, mat);
        m.name = `props:${name}:detail:${mat.userData?.propMaterial || 'mat'}`;
        m.castShadow = false;
        m.receiveShadow = true;
        tagMesh(m, d.detail, mat);
        detail.add(m);
        stats.draws++;
      }
      if (detail.children.length) {
        near.add(detail);
        detailGroups.push(detail);
      }
      /* THREE.LOD switches on the distance to the LOD's own origin, so a district whose
         radius is 50 m must not switch at 60 m — a corner 10 m from the camera would
         pop to its shell. */
      const bb = new THREE.Box3();
      near.traverse((o) => {
        if (o.isMesh && o.geometry?.boundingBox) bb.union(o.geometry.boundingBox);
      });
      const lodDist = bb.isEmpty() ? 70 : bb.getSize(_v2).length() * 0.5 + 45;
      /* contact grime — drawn after opaque, polygon-offset onto the ground */
      for (const [mat, geo] of d.contact.buildGrouped(() => palette.contact(contactAlpha))) {
        geometries.push(geo);
        const m = new THREE.Mesh(geo, mat);
        m.name = `props:${name}:contact`;
        m.castShadow = false;
        m.receiveShadow = false;
        m.renderOrder = 2;
        near.add(m);
        stats.draws++;
        void mat;
      }
      if (!any && !near.children.length) continue;
      lod.addLevel(near, 0);
      if (!d.shell.isEmpty()) {
        const far = new THREE.Group();
        far.name = `props:${name}:far`;
        for (const [mat, geo] of d.shell.buildGrouped(resolve)) {
          geometries.push(geo);
          const m = new THREE.Mesh(geo, mat);
          m.castShadow = true;
          m.receiveShadow = true;
          tagMesh(m, d.shell, mat);
          far.add(m);
        }
        lod.addLevel(far, lodDist);
      }
      if (!bb.isEmpty()) {
        bb.getCenter(_v);
        lod.position.copy(_v);
        for (const lv of lod.levels) lv.object.position.copy(_v).negate();
      }
      root.add(lod);
    }
  }

  function applyQuality() {
    const t = tier();
    const show = t !== 'low';
    for (const g of detailGroups) g.visible = show;
    const shadows = ctx.settings?.get?.('shadows') !== false;
    root?.traverse((o) => {
      if (o.isMesh && o.userData?.prop) o.castShadow = shadows && o.parent?.name?.indexOf('detail') < 0;
    });
  }

  function teardown() {
    for (const b of bodies) {
      try {
        ctx.physics?.removeBody?.(b);
      } catch {
        /* best effort */
      }
    }
    bodies.length = 0;
    for (const l of lights) {
      try {
        ctx.lighting?.removeLight?.(l);
      } catch {
        /* best effort */
      }
    }
    lights.length = 0;
    for (const g of geometries) {
      try {
        g.dispose();
      } catch {
        /* best effort */
      }
    }
    geometries.length = 0;
    if (root) {
      root.clear();
    }
    districts.clear();
    placed.length = 0;
    dynamics.length = 0;
    detailGroups.length = 0;
    grid.clear();
    stats.props = 0;
    stats.rejected = 0;
    stats.draws = 0;
    stats.triangles = 0;
    stats.colliders = 0;
    stats.dynamic = 0;
  }

  function now() {
    return typeof performance !== 'undefined' ? performance.now() : Date.now();
  }

  /* -------------------------------------------------------------------- api */

  const api = {
    ready: false,
    root: null,
    stats,
    types: () => TYPES.slice(),
    districts: () => DISTRICTS.slice(),
    materials: () => Object.keys(PROP_MATS),

    /** @see PLACEMENT OPTIONS in the file header */
    spawn(type, transform, opts) {
      if (!palette) return null;
      try {
        return spawn(type, transform, opts);
      } catch (err) {
        warn(`spawn("${type}") failed`, err);
        return null;
      }
    },

    list(filter) {
      if (!filter) return placed.slice();
      if (typeof filter === 'string') return placed.filter((p) => p.type === filter);
      if (typeof filter === 'function') return placed.filter(filter);
      return placed.slice();
    },

    count(type) {
      return type ? placed.reduce((n, p) => n + (p.type === type ? 1 : 0), 0) : placed.length;
    },

    remove(rec) {
      const i = placed.indexOf(rec);
      if (i < 0) return false;
      placed.splice(i, 1);
      if (rec.object) {
        rec.object.parent?.remove(rec.object);
        rec.object.traverse?.((o) => {
          if (o.isMesh) {
            try {
              o.geometry.dispose();
            } catch {
              /* best effort */
            }
          }
        });
      }
      for (const b of rec.colliders) {
        try {
          ctx.physics?.removeBody?.(b);
        } catch {
          /* best effort */
        }
      }
      if (rec.body) {
        try {
          ctx.physics?.removeBody?.(rec.body);
        } catch {
          /* best effort */
        }
        const di = dynamics.findIndex((d) => d.rec === rec);
        if (di >= 0) dynamics.splice(di, 1);
      }
      return true;
    },

    /** Large static blockers, for AI/nav consumers that want to avoid driving through a car. */
    footprints() {
      return placed
        .filter((p) => p.kind !== 'flat' && p.radius > 0.6)
        .map((p) => ({ type: p.type, x: p.position.x, z: p.position.z, rx: p.footprint.rx, rz: p.footprint.rz, y0: p.footprint.y0, y1: p.footprint.y1 }));
    },

    rebuild(seed) {
      if (Number.isFinite(seed)) seedBase = seed >>> 0;
      teardown();
      try {
        build();
        applyQuality();
      } catch (err) {
        warn('rebuild failed', err);
      }
      ctx.bus?.emit?.('props:rebuilt', { count: placed.length, seed: seedBase });
      return { ...stats };
    },
  };

  ctx.props = api;

  return {
    name: 'props',
    order: 34,

    async init() {
      ctx.props = api;
      root = new THREE.Group();
      root.name = 'props';
      api.root = root;
      ctx.scene?.add(root);

      try {
        palette = new PropPalette(ctx);
        palette.registerCutouts();
        contactAlpha = radialFadeAlpha(64, 1.7);
      } catch (err) {
        warn('palette init failed', err);
        palette = palette || new PropPalette(ctx);
      }

      /* Seed our deterministic stream from the engine RNG: still reproducible, and
         rebuild(seed) can move the whole dressing pass to a different draw. */
      try {
        const v = ctx.rng ? ctx.rng() : 0.5;
        seedBase = (Math.floor(v * 0xffffffff) ^ 0x1f2e3d4c) >>> 0;
      } catch {
        seedBase = 0x1f2e3d4c;
      }

      try {
        build();
      } catch (err) {
        warn('build failed', err);
      }
      try {
        applyQuality();
      } catch (err) {
        warn('quality apply failed', err);
      }

      unsubs.push(ctx.bus?.on?.('quality:changed', () => applyQuality()) || (() => {}));

      api.ready = true;
      ctx.bus?.emit?.('props:ready', { count: placed.length, footprints: api.footprints(), stats: { ...stats } });
      if (!ctx.settings?.get?.('headless')) {
        console.log(
          `[props] ${stats.props} props (${stats.rejected} rejected), ${stats.draws} batched draws, ` +
            `${(stats.triangles / 1000) | 0}k tris, ${stats.colliders} colliders, ${stats.dynamic} dynamic, ` +
            `${stats.roofCells} roof cells, ${stats.facadePoints} facade points, ${stats.buildMs}ms`
        );
      }
    },

    update(dt) {
      // Cloth ripple rides on the shared wind globals so awnings and laundry move with
      // whatever the weather system is doing.
      try {
        palette?.tickWind(ctx.materials?.globals);
      } catch {
        /* cosmetic */
      }
      if (!dynamics.length) return;
      /* Physics owns the transform; we mirror it and keep userData.dynamic set so the
         velocity pass reprojects these correctly for motion blur and TAA. */
      for (const d of dynamics) {
        const b = d.body;
        if (!b) continue;
        const g = d.rec.object;
        if (!g) continue;
        _q.copy(b.quaternion);
        _v.copy(d.offset).applyQuaternion(_q);
        g.quaternion.copy(_q);
        g.position.copy(b.position).sub(_v);
      }
      void dt;
    },

    dispose() {
      for (const u of unsubs) {
        try {
          u();
        } catch {
          /* best effort */
        }
      }
      unsubs.length = 0;
      teardown();
      try {
        contactAlpha?.dispose();
      } catch {
        /* best effort */
      }
      palette?.dispose();
      palette = null;
      if (root) {
        ctx.scene?.remove(root);
        root = null;
      }
      api.ready = false;
      api.root = null;
    },
  };
}
