/**
 * System manifest — the boot order of the whole game. Owner: ORCHESTRATOR ONLY.
 *
 * DO NOT EDIT THIS FILE. Every module slot the project will ever need is already
 * declared here and backed by a working stub. Agents replace the *contents* of their
 * own module file; the wiring never changes, so parallel work never conflicts.
 *
 * `order` controls both init order and per-frame update order (ascending).
 */
import createTextureForge from '../materials/TextureForge.js';
import createMaterialLibrary from '../materials/MaterialLibrary.js';
import createRenderPipeline from '../render/RenderPipeline.js';
import createSky from '../render/Sky.js';
import createLighting from '../render/Lighting.js';
import createWeather from '../render/Weather.js';
import createPhysicsWorld from '../physics/PhysicsWorld.js';
import createLevel from '../world/Level.js';
import createProps from '../world/Props.js';
import createFoliage from '../world/Foliage.js';
import createDestruction from '../world/Destruction.js';
import createFXSystem from '../fx/FXSystem.js';
import createDecals from '../fx/Decals.js';
import createBallistics from '../physics/Ballistics.js';
import createAudioEngine from '../audio/AudioEngine.js';
import createPlayerController from '../player/Controller.js';
import createCameraRig from '../player/CameraRig.js';
import createWeaponSystem from '../weapons/WeaponSystem.js';
import createAISystem from '../ai/AISystem.js';
import createGameMode from '../game/GameMode.js';
import createHUD from '../ui/HUD.js';
import createMenu from '../ui/Menu.js';
import createDebugTools from '../core/DebugTools.js';

export const MANIFEST = [
  { name: 'textures', order: 10, factory: createTextureForge },
  { name: 'materials', order: 12, factory: createMaterialLibrary },
  { name: 'pipeline', order: 20, factory: createRenderPipeline },
  { name: 'sky', order: 22, factory: createSky },
  { name: 'lighting', order: 24, factory: createLighting },
  { name: 'weather', order: 26, factory: createWeather },
  { name: 'physics', order: 30, factory: createPhysicsWorld },
  { name: 'level', order: 32, factory: createLevel },
  { name: 'props', order: 34, factory: createProps },
  { name: 'foliage', order: 36, factory: createFoliage },
  { name: 'destruction', order: 38, factory: createDestruction },
  { name: 'fx', order: 40, factory: createFXSystem },
  { name: 'decals', order: 42, factory: createDecals },
  { name: 'ballistics', order: 44, factory: createBallistics },
  { name: 'audio', order: 50, factory: createAudioEngine },
  { name: 'player', order: 60, factory: createPlayerController },
  { name: 'cameraRig', order: 62, factory: createCameraRig },
  { name: 'weapons', order: 70, factory: createWeaponSystem },
  { name: 'ai', order: 80, factory: createAISystem },
  { name: 'game', order: 90, factory: createGameMode },
  { name: 'hud', order: 95, factory: createHUD },
  { name: 'menu', order: 97, factory: createMenu },
  { name: 'debug', order: 999, factory: createDebugTools },
];

export default MANIFEST;
